// src/components/Navbar.jsx
import AnchorLink from "react-anchor-link-smooth-scroll";
import { Link, useLocation } from "react-router";

function Navbar() {
  const location = useLocation();
  const isHome = location.pathname === "/" || location.hash === "#home";

  const navLinks = [
    { label: "About", hash: "#about" },
    { label: "Projects", hash: "#projects" },
    { label: "Contact", hash: "#contact" },
  ];

  return (
    <div
      id="home"
      className="bg-black/30 text-white backdrop-blur-lg fixed top-0 inset-x-0 z-50"
    >
      <nav className="flex items-center justify-between px-3 md:px-5 lg:px-0 py-5 max-w-4xl xl:max-w-5xl  mx-auto">
        <h1 className="text-3xl font-semibold text-white/80">
          {isHome ? (
            <AnchorLink href="#home">Jony</AnchorLink>
          ) : (
            <Link to="/">Jony</Link>
          )}
        </h1>

        <ul className="flex items-center gap-7 text-sm md:text-base">
          {navLinks.map((item) => (
            <li
              key={item.hash}
              className="hover:font-semibold hover:text-white/80 transition-all hover:underline underline-offset-4 decoration-2 duration-300 cursor-pointer text-white/70"
            >
              {isHome ? (
                <AnchorLink offset="100" href={item.hash}>
                  {item.label}
                </AnchorLink>
              ) : (
                <Link to={`/${item.hash}`}>{item.label}</Link>
              )}
            </li>
          ))}
        </ul>
      </nav>
    </div>
  );
}

export default Navbar;

// src/app/portfolio-Website/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink,RouterLinkActive],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.scss',
})
export class NavbarComponent {}

<div class="mx-auto container">
  <div class="flex items-center justify-between pt-7 mx-3 text-sm sm:text-base">
    <img
      src="/public/assets/file.png"
      alt="logo"
      class="w-10 h-10 sm:w-12 sm:h-12 cursor-pointer"
      routerLink="/"
    />
    <div class="flex gap-4 sm:gap-5 md:gap-10 text-white text-sm">
      <a
        href="#about"
        class="hover:text-white hover:scale-125 transition-transform duration-300"
        routerLink="/about"
        routerLinkActive="active"
        ariaCurrentWhenActive="page"
        >About</a
      >
      <a
        href="#skill"
        class="hover:text-white hover:scale-125 transition-transform duration-300"
        routerLink="/skill"
        routerLinkActive="active"
        ariaCurrentWhenActive="page"
        >Skill</a
      >
      <a
        href="#portfolio"
        class="hover:text-white hover:scale-125 transition-transform duration-300"
        routerLink="/portfolio"
        routerLinkActive="active"
        ariaCurrentWhenActive="page"
        >Portfolio</a
      >
      <a
        href="#contact"
        class="hover:text-white hover:scale-125 transition-transform duration-300"
        routerLink="/contact"
        routerLinkActive="active"
        ariaCurrentWhenActive="page"
        >Contact</a
      >
    </div>
  </div>
</div>
